name: Makefile CI

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: | 
        make
        make ttcpad
      
    - name: Process font
      run: ./ttcpad font.ttc font1.ttc

    - uses: actions/upload-artifact@v3
      with:
        name: font1.ttc
        path: ${{ github.workspace }}
    
    - uses: actions/upload-artifact@v3
      with:
        name: ttcpad
        path: ${{ github.workspace }}
