name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Process font
      run: ttcpad font.ttc

    - uses: actions/upload-artifact@v3
      with:
        name: font1.ttc
        path: ${{ github.workspace }}
